<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
'Accounting Admission:' => '会计门票：',
  'Address of actual location:' => '实际位置地址：',
  'Address:' => '地址：',
  'Admission Director:' => '招生主任：',
  'BIN 1102721007168 INN 2721179894 CAT 272101001' => '该BIN 1102721007168 INN 2721179894 CAT 272101001',
  'Certificate of state registration of legal entities registered with the Inspectorate of the Federal Tax Service for the Central District of Khabarovsk №001723435 series of 27 November  2010' => '与联邦税务局的监察局哈巴罗夫斯克的中心区注册的法人实体的国家注册证书№001723435系列27 2010年11月',
  'Closed: Saturday, Sunday' => '休息日：周六，周日',
  'Content of the common property depending on the composition, design features, the degree of physical wear and tear and maintenance &nbsp; the status of the common property, as well as depending on the geodetic and climatic conditions of the location of the house includes:' => '依赖于组合物中，设计特性，物理磨损和维护＆NBSP程度的共同属性的内容;共同财产，以及对房子的位置的大地测量和气候条件不同的状态包括：',
  'Current fixing and Repair' => '当前的固定和维修',
  'Director:' => '导演：',
  'During business hours' => '在营业时间',
  'Friday' => '星期五',
  'Information about the services rendered by the company "JUBILEE»' => '有关该公司 "JUBILEE" 提供的服务信息',
  'Khabarovsk, Gorkogo 60' => '哈巴罗夫斯克，Gorkogo 60',
  'Khabarovsk, Gorkogo 60B' => '哈巴罗夫斯克，Gorkogo 60B',
  'Kim Sergey Voncherovich' => 'Kim Sergey Voncherovich',
  'LLC  "JUBILEE" manages content, repair and overhaul of the housing stock' => '有限责任公司 "JUBILEE" 管理内容，修理和大修住房存量',
  'LLC "JUBILEE" ' => '有限责任公司"JUBILEE"',
  'Maintenance of lifting equipment;' => '起重设备维护;',
  'Maintenance of metering devices;' => '计量设备的维护;',
  'Manager:' => '经理：',
  'Monday' => '星期一',
  'Monday - Thursday' => '周一 - 周四',
  'Monday-Friday: from 9-00 to 17-00' => '周一至周五：从9-00到17-00',
  'Other services:' => '其他服务：',
  'Postal address:' => '邮政地址：',
  'Services associated with the achievement of the control objectives of the apartment building' => '随着公寓大楼的控制目标的实现相关的服务',
  'The list of apartment buildings under management' => '管理下的公寓楼的名单',
  'account balances on personal accounts;' => '帐户个人账户余额;',
  'payments to utility services providers;' => '公用服务提供商的计算;',
  'cleaning and sanitary cleaning of the common areas, as well as land section, which is part of the common property;' => '清洁和公共区域的卫生清洁，以及土地款，这是共同财产的一部分;',
  'collection and disposal of municipal solid waste;' => '收集和处置城市生活垃圾;',
  'conduct claim work with the residents, with the owners and tenants of non-residential facilities;' => '随着人口的行为索赔工作中，与业主和非住宅设施的住户;',
  'conducting clearing personal accounts for low-quality provision of utility services, in connection with the temporary absence of living at the place of registration;' => '开展低质量提供公用事业服务结算个人账户，与临时缺席住在注册地的连接;',
  'content and care elements of landscaping and beautification;' => '绿化，美化的内容和关怀的元素;',
  'contracts from behalf of owners of premises in an apartment building contracts on the use of common property owners of premises in an apartment building, including the installation of fiber-optic communication lines and telecommunications equipment, installation contracts and maintenance of advertising structures, signage and other information structures.' => '关于使用在公寓大楼楼宇共同财产所有人，包括安装的光纤通信线路和通信设备，安装合同和广告结构标牌的维护和一座公寓楼的合同，从代表楼宇业主的合同其他信息结构',
  'control over the implementation of agreements;' => '控制协议的执行情况;',
  'design of the personal account, the changes in the personal account;' => '个人账户的设计中，改变个人账户;',
  'disinfection, disinfestation common property of an apartment building;' => '消毒，公寓楼的灭虫共同财产;',
  'examination, diagnosis, and insurance of lifting equipment;' => '检查，诊断和起重设备的保险;',
  'fire safety measures in accordance with the Russian legislation on fire safety;' => '按照消防安全的俄罗斯立法消防安全措施;',
  'holding charges on personal accounts;' => '永保个人账户收费;',
  'inspection of the common property, ensuring the timely identification mismatch common property law requirements state the Russian Federation, as well as security threats to the lives and health of citizens;' => '共同财产的检查，确保及时发现不匹配共同财产的法律要求规定，俄罗斯联邦，以及对生活和公民的卫生安全威胁;',
  'integrated processing payments of the residents;' => '综合人口处理付款;',
  'lighting of public spaces;' => '公共场所的照明。',
  'maintain a database of technical condition of apartment buildings, making repairs, inspections, work performed, payment calculation base data, with the formation of each year during the first quarter of the current year for each apartment building financial report for the previous year;' => '保持的公寓楼的技术状况的数据库，进行维修，检查，完成的工作，付款计算基数的数据，每年的本年度每个公寓楼为上一年度财务报告的第一季度的形成;',
  'maintenance of ventilation channels;' => '风道的维护;',
  'monthly payment and payment for utility services issue a single payment document;' => '每月支付和公共设施服务问题单付款单据支付;',
  'organizing and providing round the clock emergency service dispatcher of apartment buildings;' => '组织和提供全方位公寓楼的时钟紧急服务调度员;',
  'receive payments from the residents for housing, utilities and other services;' => '接收来自人口对住房，公用事业及其他服务费;',
  'service-house gas equipment;' => '服务内部气体设备;',
  'sign contracts with contractors to perform work on the content, the current and overhaul of the common property of the apartment building and its preparation for seasonal operation, contracts with resources organizations for the supply of resources;' => '注册与承包商合同上的内容，电流和建筑物及其季节性运行，具有资源，组织资源的供应合同准备的共同财产进行检修工作;',
  'maintenance  temperature according to Russian Federation legislation and humidity in common areas;' => '安装了俄罗斯联邦立法的温度和湿度的公共区域软件;',
  'the collection, processing payments from the residents and settlements with the residents;' => '收集，从人口和人口聚居处理付款;',
  'the conclusion of contracts for the maintenance and repair of common property with the tenants and owners of non-residential premises;' => '为维护，并与住户和非住宅楼宇业主共同财产的修理合同的结论;',
  'the issuance of extracts from the personal account;' => '从个人账户提取物的发放;',
  'Business hours:' => '营业时间:'
];
