<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
'Are you sure you want to delete this item?' => '你确定要删除这个项目吗？',
    'Body' => '身体',
    'Contacts' => '联系人',
    'Create' => '创建',
    'Create Poll' => '创建民意调查',
    'Create Polls' => '创建民意调查',
    'Create Polls Answers' => '创建民意调查答案',
    'Create Polls Result' => '创建民意调查结果',
    'Created at' => '创建时间',
    'Date begin' => '开始日期',
    'Date end' => '结束日期',
    'Delete' => '删除',
    'Email' => '电子邮件',
    'Id User' => 'ID用户',
    'Name' => '名称',
    'Number of answers' => '的回答数',
    'Polls' => '民意调查',
    'Polls Answers' => '民意调查答案',
    'Polls Results' => '民意调查结果',
    'Question' => '问题',
    'Reset' => '复位',
    'Search' => '搜索',
    'Subject' => '主题',
    'Submit' => '提交',
    'Update' => '更新',
    'Update {modelClass}: ' => '更新{modelClass}',
    'User IP' => '用户IP',
    'User host' => '用户主机',
    'Verification Code' => '验证码',
    'anonymous answers' => '匿名回答',
    'answer' => '答案',
    'multiple answer' => '多种答案',
    'random order' => '随机顺序',
    'show number of votes' => '投票显示数',
    '№ answer' => '№回答',
    '№ poll' => '№民意调查',
];
