<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Letter' => '子',
    'A you sure you want to delete' => '一个你确定要删除',
    'Vote' => '投票',
    'Create' => '创建',
    'Create house' => '创建房子',
    'Create answer' => '创建答案',
    'House' => '房子',
    'Houses' => '房子',
    'Update' => '更新',
    'Search' => '搜索',
    'Map' => '地图',
    'Polls' => '民意调查',
    'Answers' => '答案',
    'Cancel' => '取消',
    'Create poll' => '创建民意调查',
    'Delete' => '删除',
    'Street' => '街',
    'Number of answers' =>'的回答数',
    'Date begin' => '开始日期',
    'Date end' => '日期结束',
    'Answer' => '答案',
    '№ poll' => '№调查',
    '№ answer' => '№回答',
    'Home' => '首页',
    'House company' =>'屋公司',
    'Admin' => '管理员',
    'House company. Admin panel' => '房屋维修公司。管理面板',
    'Question' => '问题',
    'Update Polls' => '更新投票',
    'Anonymous votes' => '匿名投票',
    'Allow multiple' => '允许多个',
    'Random order of answers'=>'的回答随机秩序',
    'Show votes' => '显示票',
    'Allow multiple answers' => '允许多个答案',
    'Display answers in random order' => '按随机顺序显示答案',
    'Anonymous votes' => '匿名投票',
    'Action' => '操作',
    'HOME' => '首页',
    'ABOUT' => '关于',
    'INFO' => '信息',
    'SIGN UP' => '注册',
    'LOG IN' => '登录',
    'CONTACTS' => '联系',
    'POLL' => '轮询',
    'Number of answers' =>'的回答数',
    '№ poll' => '№调查',
    '№ answer' => '№回答',
    'Id User' => 'ID用户',
    'House</br>maintenance</br>company'=>'房屋</br>维修</br>公司',
    'Info' => '信息',
    'Reports' => '报告',
    'Agreements' => '协议',
    'Minutes' => '纪要',
    'Price' => '价格',
    'More...' => '更多...',
    'Pasports' => '护照',
    'Administrative proceedings' => '行政诉讼',
    'About' => '关于',
     
     
];
