<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Accounting Admission:' => '',
    'Address of actual location:' => '',
    'Address:' => '',
    'Admission Director:' => '',
    'BIN 1102721007168 INN 2721179894 CAT 272101001' => '',
    'Certificate of state registration of legal entities registered with the Inspectorate of the Federal Tax Service for the Central District of Khabarovsk №001723435 series of 27 November  2010' => '',
    'Closed: Saturday, Sunday' => '',
    'Content of the common property depending on the composition, design features, the degree of physical wear and tear and maintenance &nbsp; the status of the common property, as well as depending on the geodetic and climatic conditions of the location of the house includes:' => '',
    'Current fixing and Repair' => '',
    'Director:' => '',
    'During business hours' => '',
    'Friday' => '',
    'Information about the services rendered by the company "JUBILEE»' => '',
    'Khabarovsk, Gorkogo 60' => '',
    'Khabarovsk, Gorkogo 60B' => '',
    'Kim Sergey Voncherovich' => '',
    'LLC  "JUBILEE" manages content, repair and overhaul of the housing stock' => '',
    'LLC "JUBILEE" ' => '',
    'Maintenance of lifting equipment;' => '',
    'Maintenance of metering devices;' => '',
    'Manager:' => '',
    'Monday' => '',
    'Monday - Thursday' => '',
    'Monday-Friday: from 9-00 to 17-00' => '',
    'Other services:' => '',
    'Postal address:' => '',
    'Services associated with the achievement of the control objectives of the apartment building' => '',
    'The list of apartment buildings under management' => '',
    'account balances on personal accounts;' => '',
    'calculations of utility services providers;' => '',
    'cleaning and sanitary cleaning of the common areas, as well as land section, which is part of the common property;' => '',
    'collection and disposal of municipal solid waste;' => '',
    'conduct claim work with the population, with the owners and tenants of non-residential facilities;' => '',
    'conducting clearing personal accounts for low-quality provision of utility services, in connection with the temporary absence of living at the place of registration;' => '',
    'content and care elements of landscaping and beautification;' => '',
    'contracts from behalf of owners of premises in an apartment building contracts on the use of common property owners of premises in an apartment building, including the installation of fiber-optic communication lines and telecommunications equipment, installation contracts and maintenance of advertising structures, signage and other information structures.' => '',
    'control over the implementation of agreements;' => '',
    'design of the personal account, the changes in the personal account;' => '',
    'disinfection, disinfestation common property of an apartment building;' => '',
    'examination, diagnosis, and insurance of lifting equipment;' => '',
    'fire safety measures in accordance with the Russian legislation on fire safety;' => '',
    'holding charges on personal accounts;' => '',
    'inspection of the common property, ensuring the timely identification mismatch common property law requirements state the Russian Federation, as well as security threats to the lives and health of citizens;' => '',
    'integrated processing payments of the population;' => '',
    'lighting of public spaces;' => '',
    'maintain a database of technical condition of apartment buildings, making repairs, inspections, work performed, payment calculation base data, with the formation of each year during the first quarter of the current year for each apartment building financial report for the previous year;' => '',
    'maintenance of ventilation channels;' => '',
    'monthly payment and payment for utility services issue a single payment document;' => '',
    'organizing and providing round the clock emergency service dispatcher of apartment buildings;' => '',
    'receive payments from the population for housing, utilities and other services;' => '',
    'service-house gas equipment;' => '',
    'sign contracts with contractors to perform work on the content, the current and overhaul of the common property of the apartment building and its preparation for seasonal operation, contracts with resources organizations for the supply of resources;' => '',
    'software installed Russian Federation Temperature legislation and humidity in common areas;' => '',
    'the collection, processing payments from the population and settlements with the population;' => '',
    'the conclusion of contracts for the maintenance and repair of common property with the tenants and owners of non-residential premises;' => '',
    'the issuance of extracts from the personal account;' => '',
    '1. Content of the common property depending on the composition, design features, the degree of physical wear and tear and maintenance &nbsp; the status of the common property, as well as depending on the geodetic and climatic conditions of the location of the house includes:' => '@@@@',
    '2. Current fixing and Repair' => '@@@@',
    '3. Services associated with the achievement of the control objectives of the apartment building' => '@@@@',
];
