<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'CLEANING' => '',
    'CLIMATE SUPPORT' => '',
    'Ensuring the optimum temperature and humidity in the common areas' => '',
    'GENERAL INSPECTION' => '',
    'Inspection of the common property of homes to identify inconsistencies with legal requirements of the Russian Federation' => '',
    'LIGHTING' => '',
    'OPENNESS' => '',
    'PERSPECTIVE' => '',
    'PROFESSIONALISM' => '',
    'Support for lighting of common areas in apartment buildings' => '',
    'THE LIST OF SERVICES' => '',
    'Timely cleaning and sanitary cleaning of the common areas' => '',
    'WE ALWAYS EMIT A HUGE POSITIVE CHARGE AND BUILD LONG-TERM RELATIONSHIPS WITH OUR RESIDENTS.' => '',
    'WE PROVIDE FREE RESIDENTS ACCESS TO INFORMATION ON ACTIVITIES, TARIFFS AND SERVICES, REGULATIONS AND ACCEPTANCE OF PAYMENT.' => '',
    'WE PROVIDE QUALITY MAINTENANCE SERVICES, MAINTENANCE AND REPAIRS OF APARTMENT BUILDINGS. RESIDENT - OUR TOP PRIORITY!' => '',
    'We provide a full range of housing services for the management and maintenance of apartment buildings in the city of Khabarovsk.' => '',
];
