<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
  'BALANS.pdf' =>  'БАЛАНС.pdf',
    'Financial Statements for 2014 g.pdf' =>    'Бухгалтерская отчетность за 2014 г.pdf',
    'The balance sheet for 2013 g.docx' =>    'Бухгалтерский баланс за 2013 г.docx',
    'Knyazhnichnaya3,5,5A.docx Contract Management' =>    'Договор управления Княжничная3,5,5А.docx',
    'Agreement on 05.04.14 MKD management Knyazhnichnaya 1.docx' =>    'Договор управления МКД от 04.05.14 Княжничная 1.docx',
    'Contract Management from MKD 04/30/14 ul.Gorkogo 62A.docx' =>    'Договор управления МКД от 30.04.14 Ул.Горького 62А.docx',
    'Deed MKD №13 from 29.03.11 Gorkogo 60A.docx' =>    'Договор управления МКД №13 от 29.03.11 Горького 60А.docx',
    'Contract №203 from 01.11.11 MKD control Gorkogo 60B.docx' =>    'Договор №203 управления МКД от 01.11.11 Горького 60Б.docx',
    'Contract №203 from 01.11.11 MKD control Gorkogo 60V.docx' =>    'Договор №203 управления МКД от 01.11.11 Горького 60В.docx',
    'Use of a common imuschestva.pdf' =>    'Использование общего имущества.pdf',
    'Price-fixing on vodootvedenie.docx' =>    'Об установлении цен на водоотведение.docx',
    'Price-fixing on hol.vodu.docx' =>    'Об установлении цен на хол.воду.docx',
    'Price-fixing on el.energiyu.docx' =>    'Об установлении цен на эл.энергию.docx',
    'Report for the 2012 Bolshaya 12.pdf' =>    'Отчет за 2012 ул.Большая 12.pdf',
    'Report for 2013 Gorkogo 60 a.pdf' =>    'Отчет за 2013 Горького 60 а.pdf',
    'Report for 2013 Gorkogo 60B.pdf' =>    'Отчет за 2013 Горького 60Б.pdf',
    'Report for 2013 Gorkogo 60V.pdf' =>    'Отчет за 2013 Горького 60В.pdf',
    'Report for 2013 Gorkogo 62 a.pdf' =>    'Отчет за 2013 Горького 62 а.pdf'
    'Report for 2013 Gorkogo 62.pdf' =>    'Отчет за 2013 Горького 62.pdf',
    'Report for 2013 Knyazhnichnaya 1.pdf' =>    'Отчет за 2013 Княжничная 1.pdf',
    'Report for 2013 Knyazhnichnaya 3.pdf' =>    'Отчет за 2013 Княжничная 3.pdf',
    'Report for 2013 Knyazhnichnaya 5.pdf' =>    'Отчет за 2013 Княжничная 5.pdf',
    'Report for 2013 Knyazhnichnaya 5A.pdf' =>    'Отчет за 2013 Княжничная 5А.pdf',
    'Report for the 2013 Bolshaya 12.pdf' =>    'Отчет за 2013 ул.Большая 12.pdf',
    'Report for 2014 Gorkogo 60 a.pdf' =>    'Отчет за 2014 Горького 60 а.pdf',
    'Report for 2014 Gorkogo 60B.pdf' =>    'Отчет за 2014 Горького 60Б.pdf',
    'Report for 2014 Gorkogo 60V.pdf' =>    'Отчет за 2014 Горького 60В.pdf',
    'Report for 2014 Gorkogo 62 a.pdf' =>    'Отчет за 2014 Горького 62 а.pdf',
    'Report for 2014 Gorkogo 62.pdf' =>    'Отчет за 2014 Горького 62.pdf',
    'Report for 2014 Knyazhnichnaya 1.pdf' =>    'Отчет за 2014 Княжничная 1.pdf',
    'Report for 2014 Knyazhnichnaya 3.pdf' =>    'Отчет за 2014 Княжничная 3.pdf',
    'Report for 2014 Knyazhnichnaya 5.pdf' =>    'Отчет за 2014 Княжничная 5.pdf',
    'Report for 2014 Knyazhnichnaya 5A.pdf' =>    'Отчет за 2014 Княжничная 5А.pdf',
    'PASSPORT OBEKTOV.xlsx' =>    'ПАСПОРТ ОБЪЕКТОВ.xlsx',
    'THE GOVERNMENT OF THE KHABAROVSK TERRITORY # 388-pr of 31.10.12 (in the red. From 12.12.14) .docx' =>    'ПОСТАНОВЛЕНИЕ ПРАВИТЕЛЬСТВА ХАБАРОВСКОГО КРАЯ №388-пр от 31.10.12 (в ред. от 12.12.14).docx',
    'Government Decree №174-Hab.kraya forth from 28.06.13.docx' =>    'Постановление Правительства Хаб.края №174-пр от 28.06.13.docx',
    'Project dogovora.doc' =>    'Проект договора.doc',
    'Minutes 15.06.15 ul.Knyazhnichnaya 5A.docx' =>    'Протокол 15.06.15 ул.Княжничная 5А.docx',
    'Meeting Minutes 06/15/15 Knyazhnichnaya 5.docx' =>    'Протокол собрания 15.06.15 Княжничная 5.docx',
    'Minutes of the meeting of owners Gorkogo 62.docx' =>    'Протокол собрания собственников Горького 62.docx',
    'Cost of works (services) MKD management Gorkogo 62A.doc' =>    'Стоимость работ (услуг) по управлению МКД Горького 62А.doc',
    'The cost of ICM management services Gorkogo 60B.docx' =>    'Стоимость работ услуг по управлению МКД Горького 60Б.docx',
    'The cost of ICM management services Gorkogo 60V.docx' =>    'Стоимость работ услуг по управлению МКД Горького 60В.docx',
    'The cost of ICM management services Knyazhnichnaya 5A, 3,5.docx' =>    'Стоимость работ услуг по управлению МКД Княжничная 5А,3,5.docx',
    'The cost of works on the ICM management services Gorkogo 60A.doc' =>    'Стоимость работ, услуг по управлению МКД Горького 60А.doc',
    'The cost of works on the ICM management services Knyazhnichnaya 1.doc' =>    'Стоимость работ, услуг по управлению МКД Княжничная 1.doc',
    "Tariffs on utility services 2015.docx '=>' ',;    'Тарифы на коммунальные услуги на 2015.docx',
    'Report for 2015 Gorkogo 60A.pdf' =>    'отчет за 2015 Горького 60А.pdf',
    'Report for 2015 Gorkogo 60V.pdf' =>    'отчет за 2015 Горького 60В.pdf',
    'Report for 2015 Gorkogo 62.pdf' =>    'отчет за 2015 Горького 62.pdf',
    'Report for 2015 Gorkogo 62A.pdf' =>    'отчет за 2015 Горького 62А.pdf',
    'Report for 2015 Knyazhnichnaya 1.pdf' =>    'отчет за 2015 Княжничная 1.pdf',
    'Report for 2015 Knyazhnichnaya 3.pdf' =>    'отчет за 2015 Княжничная 3.pdf',
    'Report for 2015 Knyazhnichnaya 5.pdf' =>    'отчет за 2015 Княжничная 5.pdf',
    'Report for 2015 Knyazhnichnaya 5A.pdf' =>    'отчет за 2015 Княжничная 5А.pdf',
];
