<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
     'Letter' => 'Буква номера',
     'A you sure you want to delete' => 'Вы уверены, что хотите удалить?',
     'Vote' => 'Голосование',
     'Create' => 'Добавить',
     'Create house' => 'Добавить дом',
     'Create answer' => 'Добавить ответ',
     'House' => 'Дом',
     'Houses' => 'Дома',
     'Update' => 'Изменить',
     'Search' => 'Искать', 
     'Map' => 'Карта',
     'Polls' => 'Опросы',
     'Answers' => 'Ответы',
     'Cancel' => 'Отменить',
     'Create poll' => 'Создать опрос',
     'Delete' => 'Удалить',
     'Street' => 'Улица',
     'Number of answers' => 'Количество ответов',
     'Date begin' => 'Начало опроса',
     'Date end' => 'Окончание опроса',
     'Answer' => 'Ответ',
     '№ poll' => '№ опроса',
     '№ answer' => '№ ответа',
     'Home' => 'Главная',
     'House company' => 'Управляющая компания',
     'Admin' => 'Администрирование',
     'House company. Admin panel' => 'Управляющая компания. Админка',
     'Question' => 'Вопрос',
     'Update Polls' => 'Изменить опрос',
     'Anonymous votes' => 'Анонимное голосование',
     'Allow multiple' => 'Множественный ответ',
     'Random order of answers' => 'Случайный порядок вопросов',
     'Show votes' => 'Показывать результаты',
     'Allow multiple answers' => 'Несколько ответов',
     'Display answers in random order' => 'Показывать ответы в случайном порядке',
     'Anonymous votes' => 'Разрешить голосование без регистрации',
     'Action' => 'Действия',
     'HOME' => 'ГЛАВНАЯ',
     'ABOUT' => 'О КОМПАНИИ',
     'INFO' => 'ИНФОРМАЦИЯ',
     'SIGN UP' => 'РЕГИСТРАЦИЯ',
     'LOG IN' => 'ВОЙТИ',
     'CONTACTS' => 'КОНТАКТЫ',
     'POLL' => 'ОПРОС',
     'Number of answers' => 'Количество ответов',
     '№ poll' => '№ опроса',
     '№ answer' => '№ ответа',
     'Id User' => 'Номер пользователя',
     'House</br>company' => 'Управляющая </br>компания',
     'Info' => 'Информация',
     'Reports' => 'Отчеты',
     'Agreements' => 'Договора',
     'Minutes' => 'Протоколы',
     'Price' => 'Стоимость',
     'More...' => 'Прочее',
     'Passports' => 'Паспорта объектов',
     'Administrative proceedings' => 'Административная ответственность',
     
     
];
