<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Буква номера' => 'Letter',
    'Варианты ответов' => 'Answers',
    'Вы уверены, что хотите удалить?' => 'A you sure you want to delete',
    'Голосование' => 'Vote',
    'Добавить' => 'Create',
    'Добавить дом' => 'Create house',
    'Добавить ответ' => 'Create answer',
    'Дом' => 'House',
    'Дома' => 'Houses',
    'Изменить' => 'Update',
    'Искать' => 'Search',
    'Карта' => 'Map',
    'Опросы' => 'Polls',
    'Ответы' => 'Answers',
    'Отменить' => 'Cancel',
    'Создать опрос' => 'Create poll',
    'Удалить' => 'Delete',
    'Улица' => 'Street',
    'вопрос в опросе' => 'Answer',
    'количество ответов' => 'Number of answers',
    'начало опроса' => 'Date begin',
    'окончание опроса' => 'Date end',
    'ответ' => 'Answer',
    '№ опроса' => '№ poll',
    '№ ответа' => '№ answer',
    'Главная' => 'Home',
    'Управляющая компания' => 'House company',
];
